<?php

/**
 * @file
 * Contains lieplus.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function lieplus_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the lieplus module.
    case 'help.page.lieplus':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('head hunter system for GoldLink') . '</p>';
      return $output;

    default:
  }
}
